name: Validate Workflows

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    container:
      image: docker.io/rhysd/actionlint:1.7.7
    steps:
      - name: Run actionlint
        run: actionlint -color "${GITHUB_WORKSPACE}/.github/workflows/"
